### ISSUE TITLE
UX improvements

### ISSUE THREAD

**Issue by cyrilletuzi** [cyrilletuzi/vscode-angular-schematics#34]
- [x] use `x-prompt` messages when available > PR #33
- [x] pre-select required options > PR #36
- [x] filter unecessary options (`name` ?) > PR #36
- [x] pro-tip for path and `project` telling they can be auto-detected by the extension > PR #37 
- [x] many users discover this extension via a pack, then having not read the instructions, so what they'll see is the Angular view: but it's easier to launch the schematics from a right click (so path and projects are inferred), so instructions should be added in the view
- [x] pro-tip for `module` option, saying it's already auto-detected by the CLI
- [x] link to explanation for components predefined choices
- [ ] when multiple collections, inform `@schematics/angular` are the default Angular CLI commands
- [x] don't propose options for direct service creation shortcut?
- [ ] maybe use VS Code >= 1.26 new QuickInput API?
- [ ] support more scenarios for jump to file

Suggestions welcomed.

**Comment by smnbbrv** [comment]
Another suggestion: when I run the command from Shift + Cmd / Ctrl + P it would make sense to write in a currently highlighted folder / file in the tree (depending on schematic :) ) and / or the currently open file

I guess the same would happen if I assign the hot keys on those lovely commands.

In order to avoid annoyed users it would be good to 
- either select the whole input that it gets directly erased if they type something else
- maybe propose currently highlighted folder in the tree **and** the currently open file in the dropdown like we have it here

![image](https://user-images.githubusercontent.com/13453858/53643899-95764480-3c35-11e9-9a0e-b77e93248510.png)

but with ability of writing own value.

In the end, helping people enter the file paths fast and reliably would become a primary feature of the tool. Because normally the file path causes problems.

Maybe it makes sense to have some sort of autocompletion for paths as well.

I didn't dig enough into developing vscode extensions, so I don't know whether it is really possible to do the things above. But, the intention is here :D

Thank you for the great tool and motivation to further develop it. Keep going! :)

**Comment by cyrilletuzi** [comment]
@smnbbrv Thanks for your feedback. As the path (and project) are already inferred when doing a right-click on a directory in the files explorer, what would be the benefit to launch the commands from the command palette instead?

**Comment by smnbbrv** [comment]
This could be useful if I open the module with CTRL + P and then want to add component. Another example is I click with mouseleft on the folder name and press a hot key. The hot key is in the end just a representation of command palette...

**Comment by tayambamwanza** [comment]
Also adding this even though vs code does not support this yet, please add icons for the options.
![generate-component](https://user-images.githubusercontent.com/11971384/56096531-c8c11a00-5ee9-11e9-9fc3-f31ec251b561.png)

**Comment by cyrilletuzi** [comment]
Hi @tayambamwanza, thanks for your feedback.

From which extension comes your screenshot?

**Comment by tayambamwanza** [comment]
@cyrilletuzi actually it's not an extension it's stackblitz, it's built into the stackblitz ide
